In [4]:
import torch
print(torch.__version__)
print("hello")

2.11.0+cpu
hello


In [9]:
a = torch.tensor([
    [1,2,3,4,5,6],
    [7,6,5,4,3,1]
    ])
print(a)

tensor([[1, 2, 3, 4, 5, 6],
        [7, 6, 5, 4, 3, 1]])


In [12]:
print(torch.ones(4,5))
print(torch.zeros(2,3))
print(torch.rand(2,5))
b = torch.tensor([
    [1,2,3,4,5,6],
    [7,6,5,4,3,1]
    ])
print(b.shape)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.4214, 0.6089, 0.4955, 0.4276, 0.2448],
        [0.1105, 0.4673, 0.5572, 0.4032, 0.3037]])
torch.Size([2, 6])


In [15]:
print(b[1,1])

tensor(6)


In [23]:
# project for liner algebra

# input x
x = torch.tensor([1,2,3,4,5,6])

# y is output 
y = torch.tensor([1,4,9,16,25,36])

y_predict = x ** 3

loss = ((( y - y_predict ) ** 2)*1.0).mean()

print("Actual Input : " , x)
print("Actual Output : " , y)
print("y_predict : " , y_predict)
print("loss: " , loss )



Actual Input :  tensor([1, 2, 3, 4, 5, 6])
Actual Output :  tensor([ 1,  4,  9, 16, 25, 36])
y_predict :  tensor([  1,   8,  27,  64, 125, 216])
loss:  tensor(7507.3335)


In [ ]:

a = torch.tensor(5.)
b = torch.tensor(6. , requires_grad=True)

# backward tell who is responble and how much 

y = a * b
z = a + b
x = a * b

y_true = torch.tensor(29.)

# print(x)
# print(y)
# print(z)

loss = (y_true  - y) ** 2

print(loss)
loss.backward()

# if b.grad is greater than 0 then decrese the value of b , if negative increase 
# it tells how to reduce the loss by changing value of b 
# b is learnable not a because requires_grad is true thats why we use tensor a special kind of data structure 
# in tensor we can change value which is helpfull in learning
print(b.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(10.)


In [ ]:
x = torch.tensor(10. , requires_grad=True)
y = torch.tensor(5.)

z = x * y
z2 = x + y
z_true = torch.tensor(40.)

loss = (z_true - z) ** 2
loss.backward()

print(x.grad)

lr = 0.1

# the suggestion is -50 we always take 10% of suggestion in general
with torch.no_grad():
    x-= (lr * x.grad)

print("final value of x :" , x.item())
print(x.grad)

# without this new grad value of x because of z2 is added in existing so output will be 100 +1= 101 not 1
x.grad.zero_()
z2.backward()
print(x.grad)


tensor(100.)
final value of x : 0.0
tensor(100.)
tensor(1.)


In [71]:
x = torch.tensor([1.,2.,3.,4.])
y_true = torch.tensor([2.,4.,6.,8.])

w = torch.tensor(0.0 , requires_grad=True)

lr = 0.1
epochs = 20

for epoch in range(epochs):
    # step 1 : find the predict value
    y_predict = x * w

    # step 2 : calculate the loss
    loss = ((y_true - y_predict) ** 2).mean()

    # step 3 : backward and grad value 

    loss.backward()

    with torch.no_grad():
        w-= lr * w.grad

    print(f"Epoch {epoch + 1}: w = {w.item():.4f} , loss = {loss.item():.4f}")
    # if we dont do this it goes in wrong direction 

    w.grad.zero_()



Epoch 1: w = 3.0000 , loss = 30.0000
Epoch 2: w = 1.5000 , loss = 7.5000
Epoch 3: w = 2.2500 , loss = 1.8750
Epoch 4: w = 1.8750 , loss = 0.4688
Epoch 5: w = 2.0625 , loss = 0.1172
Epoch 6: w = 1.9688 , loss = 0.0293
Epoch 7: w = 2.0156 , loss = 0.0073
Epoch 8: w = 1.9922 , loss = 0.0018
Epoch 9: w = 2.0039 , loss = 0.0005
Epoch 10: w = 1.9980 , loss = 0.0001
Epoch 11: w = 2.0010 , loss = 0.0000
Epoch 12: w = 1.9995 , loss = 0.0000
Epoch 13: w = 2.0002 , loss = 0.0000
Epoch 14: w = 1.9999 , loss = 0.0000
Epoch 15: w = 2.0001 , loss = 0.0000
Epoch 16: w = 2.0000 , loss = 0.0000
Epoch 17: w = 2.0000 , loss = 0.0000
Epoch 18: w = 2.0000 , loss = 0.0000
Epoch 19: w = 2.0000 , loss = 0.0000
Epoch 20: w = 2.0000 , loss = 0.0000
